#!/usr/bin/env python3
"""
fractal_cnn_train.py — Standalone training script for fractal post-decode CNN

Trains a lightweight residual CNN to recover high-frequency detail (edges, texture)
lost by fractal image compression's mandatory 2× downsampling lowpass filter.

Training data is generated by running the fractal pipeline on diverse image datasets
(Kodak-24, BSD500, DIV2K) and collecting (decoded_Y, original_Y) patch pairs.

The trained model weights are saved as fractal_cnn_weights.pt (~150KB), which ships
alongside the notebook in the repo. The CNN adds zero file size to .frac output.

Usage:
    # In Google Colab (recommended — needs GPU for fractal encoding):
    !python fractal_cnn_train.py --datasets kodak,bsd500,div2k --epochs 80 --output fractal_cnn_weights.pt

    # Or step by step:
    !python fractal_cnn_train.py --phase download   # download datasets
    !python fractal_cnn_train.py --phase generate    # generate training pairs
    !python fractal_cnn_train.py --phase train       # train the CNN

Requirements:
    pip install torch torchvision cupy-cuda12x scipy pillow
"""

import os
import sys
import math
import time
import json
import struct
import zlib
import random
import argparse
import io
from pathlib import Path

import numpy as np
from PIL import Image
from scipy.fft import dctn, idctn

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

# ─── Fractal Pipeline Constants ─────────────────────────────────────────────
BLOCK_SIZE     = 8
DOMAIN_SIZE    = 16
NUM_TRANSFORMS = 8
N_ITERATIONS   = 10

# ─── Detect GPU for fractal encoding (CuPy) ────────────────────────────────
try:
    import cupy as cp
    cp.cuda.Device(0).compute_capability
    xp = cp
    print('[fractal_cnn_train] GPU ready (CuPy)')
except Exception as e:
    xp = np
    print(f'[fractal_cnn_train] CPU fallback: {e}')


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 1: Fractal pipeline functions (copied from v7_32 notebook)
# These are needed to encode/decode images for training pair generation.
# ═══════════════════════════════════════════════════════════════════════════════

def rgb_to_ycbcr(image):
    img = image.astype(np.float32)
    m   = np.array([[ 0.299,  0.587,  0.114],
                    [-0.169, -0.331,  0.500],
                    [ 0.500, -0.419, -0.081]])
    y = img @ m.T
    y[:,:,1] += 128; y[:,:,2] += 128
    return np.clip(y, 0, 255).astype(np.uint8)


def pad_to_block_multiple(img):
    H, W = img.shape[:2]
    Hp = math.ceil(H / BLOCK_SIZE) * BLOCK_SIZE
    Wp = math.ceil(W / BLOCK_SIZE) * BLOCK_SIZE
    if Hp == H and Wp == W:
        return img, H, W
    return np.pad(img, ((0,Hp-H),(0,Wp-W),(0,0)), mode='edge'), H, W


def downsample_2x(block):
    h, w = block.shape
    return block.reshape(h//2, 2, w//2, 2).mean(axis=(1,3)).astype(np.float32)


def get_all_transforms(block):
    variants = []
    for flip in [False, True]:
        b = np.fliplr(block) if flip else block.copy()
        for r in range(4):
            variants.append(np.rot90(b, r).copy())
    return np.array(variants, dtype=np.float32)


def validate_domain_step(H_pad, W_pad, step):
    cy_max = (H_pad - DOMAIN_SIZE) // step
    cx_max = (W_pad - DOMAIN_SIZE) // step
    if cy_max > 63:
        raise ValueError(f'cy_max={cy_max} overflows 6-bit field')
    if cx_max > 63:
        raise ValueError(f'cx_max={cx_max} overflows 6-bit field')


def compute_auto_domain_step(H_pad, W_pad, budget_sec=120):
    n_blocks = (H_pad // BLOCK_SIZE) * (W_pad // BLOCK_SIZE)
    max_cand = budget_sec / (n_blocks * 2.5e-8)
    step = max(8, min(64, int(math.ceil(
        math.sqrt((H_pad * W_pad * 8) / max(max_cand, 1)) / 8)) * 8))
    while True:
        try:
            validate_domain_step(H_pad, W_pad, step)
            break
        except:
            step += 8
        if step > 256:
            break
    return step


def analyse_image(channel, time_budget_sec=120):
    H, W = channel.shape
    ch   = channel.astype(np.float32)
    Hp   = math.ceil(H / BLOCK_SIZE) * BLOCK_SIZE
    Wp   = math.ceil(W / BLOCK_SIZE) * BLOCK_SIZE

    range_vars = np.array([
        ch[ry:ry+BLOCK_SIZE, rx:rx+BLOCK_SIZE].var()
        for ry in range(0, H-BLOCK_SIZE+1, BLOCK_SIZE)
        for rx in range(0, W-BLOCK_SIZE+1, BLOCK_SIZE)
    ])
    total_blocks = len(range_vars)

    FLAT_THRESH = min(float(np.percentile(range_vars, 5)), 50.0)
    flat_mask   = range_vars < FLAT_THRESH
    flat_means  = {}
    bi = 0
    for ry in range(0, H-BLOCK_SIZE+1, BLOCK_SIZE):
        for rx in range(0, W-BLOCK_SIZE+1, BLOCK_SIZE):
            if flat_mask[bi]:
                flat_means[(ry, rx)] = float(
                    ch[ry:ry+BLOCK_SIZE, rx:rx+BLOCK_SIZE].mean())
            bi += 1

    complex_vars = range_vars[~flat_mask]
    median_var   = float(np.median(complex_vars)) if len(complex_vars) > 0 else 100.0
    auto_thresh  = float(np.clip(median_var * 0.50, 5.0, 500.0))
    auto_step    = compute_auto_domain_step(Hp, Wp, time_budget_sec)

    return {
        'error_threshold': auto_thresh,
        'domain_step':     auto_step,
        'flat_mask':       flat_mask,
        'flat_means':      flat_means,
        'median_var':      median_var,
        'total_blocks':    total_blocks,
        'range_vars':      range_vars,
    }


def build_domain_stack(channel, domain_step):
    H, W = channel.shape
    candidates, meta = [], []
    for dy in range(0, H-DOMAIN_SIZE+1, domain_step):
        for dx in range(0, W-DOMAIN_SIZE+1, domain_step):
            raw = channel[dy:dy+DOMAIN_SIZE, dx:dx+DOMAIN_SIZE]
            ds  = downsample_2x(raw)
            tfs = get_all_transforms(ds)
            for ti in range(NUM_TRANSFORMS):
                candidates.append(tfs[ti].flatten())
                meta.append((dy, dx, ti))
    dg = xp.array(np.array(candidates, dtype=np.float32))
    return dg, meta


def encode_channel_gpu(channel, cfg):
    H, W       = channel.shape
    ch         = channel.astype(np.float32)
    thresh     = cfg['error_threshold']
    step       = cfg['domain_step']
    flat_means = cfg['flat_means']

    ds, meta = build_domain_stack(ch, step)
    N = ds.shape[0]
    n_px = float(BLOCK_SIZE * BLOCK_SIZE)

    sum_d  = xp.sum(ds, axis=1)
    sum_d2 = xp.sum(ds ** 2, axis=1)
    denom  = n_px * sum_d2 - sum_d ** 2
    flat_d = xp.abs(denom) < 1e-6

    all_pos = [
        (ry, rx)
        for ry in range(0, H - BLOCK_SIZE + 1, BLOCK_SIZE)
        for rx in range(0, W - BLOCK_SIZE + 1, BLOCK_SIZE)
    ]
    total_blocks = len(all_pos)

    flat_results = {}
    search_pos   = []
    for bi, (ry, rx) in enumerate(all_pos):
        if (ry, rx) in flat_means:
            flat_results[(ry, rx)] = (0, 0, 0, 0.0, flat_means[(ry, rx)])
        else:
            search_pos.append((ry, rx))

    M = len(search_pos)

    R_np = np.stack([
        ch[ry:ry+BLOCK_SIZE, rx:rx+BLOCK_SIZE].flatten()
        for ry, rx in search_pos
    ], axis=0).astype(np.float32)
    R = xp.array(R_np)

    sum_r  = xp.sum(R, axis=1)
    sum_r2 = xp.sum(R ** 2, axis=1)

    CHUNK = M
    best_idx_all = xp.zeros(M, dtype=xp.int32)
    best_err_all = xp.full(M, xp.inf, dtype=xp.float32)
    best_cq_all  = xp.zeros(M, dtype=xp.float32)
    best_bq_all  = xp.zeros(M, dtype=xp.float32)

    offset = 0
    while offset < M:
        chunk_ok = False
        while not chunk_ok:
            try:
                end = min(offset + CHUNK, M)
                Rc  = R[offset:end]
                src = sum_r[offset:end]
                c   = end - offset

                sum_dr = Rc @ ds.T

                cq_raw = (n_px * sum_dr - sum_d[None,:] * src[:,None]) \
                         / (denom[None,:] + 1e-10)
                cq = xp.clip(cq_raw, -0.75, 0.75)
                bq = (src[:,None] - cq * sum_d[None,:]) / n_px

                cq[:, flat_d] = 0.0
                if flat_d.any():
                    bq_mean = (src / n_px)[:,None] * xp.ones(
                        (c, int(flat_d.sum())), dtype=xp.float32)
                    bq[:, flat_d] = bq_mean

                errors = (
                    cq**2 * (sum_d2[None,:] / n_px)
                    + bq**2
                    + (sum_r2[offset:end,None] / n_px)
                    + 2.0 * cq * bq * (sum_d[None,:] / n_px)
                    - 2.0 * cq * (sum_dr / n_px)
                    - 2.0 * bq * (src[:,None] / n_px)
                )

                bidx = xp.argmin(errors, axis=1)
                berr = errors[xp.arange(c), bidx]
                bcq  = cq[xp.arange(c), bidx]
                bbq  = bq[xp.arange(c), bidx]

                best_idx_all[offset:end] = bidx
                best_err_all[offset:end] = berr
                best_cq_all [offset:end] = bcq
                best_bq_all [offset:end] = bbq

                offset   += CHUNK
                chunk_ok  = True

            except Exception as e:
                if 'memory' in str(e).lower() or 'alloc' in str(e).lower():
                    CHUNK = max(64, CHUNK // 2)
                    print(f'    OOM — retrying with chunk={CHUNK}')
                else:
                    raise

    to_np = lambda x: x.get() if hasattr(x, 'get') else np.array(x)
    bidx_cpu = to_np(best_idx_all)
    berr_cpu = to_np(best_err_all)
    bcq_cpu  = to_np(best_cq_all)
    bbq_cpu  = to_np(best_bq_all)

    transforms = []
    early = 0
    si    = 0

    for bi, (ry, rx) in enumerate(all_pos):
        if (ry, rx) in flat_results:
            transforms.append(flat_results[(ry, rx)])
            early += 1
        else:
            dy, dx, ti = meta[bidx_cpu[si]]
            transforms.append((dy, dx, ti, float(bcq_cpu[si]), float(bbq_cpu[si])))
            if berr_cpu[si] <= thresh:
                early += 1
            si += 1

    flat_count = len(flat_results)
    nf = total_blocks - flat_count
    ep = (early - flat_count) / max(nf, 1)
    return transforms, ep


def decode_fractal(transforms, image_shape, n_iterations=10):
    H, W    = image_shape
    current = np.full((H, W), 128.0, dtype=np.float32)
    pos     = [(ry, rx)
               for ry in range(0, H-BLOCK_SIZE+1, BLOCK_SIZE)
               for rx in range(0, W-BLOCK_SIZE+1, BLOCK_SIZE)]
    for it in range(n_iterations):
        nxt = np.zeros((H, W), dtype=np.float32)
        for bi, (ry, rx) in enumerate(pos):
            dy, dx, ti, c, b = transforms[bi]
            raw    = current[dy:dy+DOMAIN_SIZE, dx:dx+DOMAIN_SIZE]
            domain = downsample_2x(raw)
            if ti >= 4:
                domain = np.fliplr(domain)
            domain = np.rot90(domain, ti % 4)
            nxt[ry:ry+BLOCK_SIZE, rx:rx+BLOCK_SIZE] = c * domain + b
        current = nxt
    return np.clip(current, 0, 255).astype(np.uint8)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 2: Dataset Download Helpers
# ═══════════════════════════════════════════════════════════════════════════════

def download_kodak(dest='datasets/kodak'):
    """Download Kodak-24 dataset (24 images, 768×512, lossless PNG)."""
    import requests
    os.makedirs(dest, exist_ok=True)
    base = 'http://r0k.us/graphics/kodak/kodak/'
    downloaded = []
    for i in range(1, 25):
        fname = f'kodim{i:02d}.png'
        fpath = os.path.join(dest, fname)
        if os.path.exists(fpath):
            downloaded.append(fpath)
            continue
        url = base + fname
        try:
            r = requests.get(url, timeout=30)
            if r.status_code == 200:
                with open(fpath, 'wb') as f:
                    f.write(r.content)
                downloaded.append(fpath)
                print(f'  Downloaded {fname}')
        except Exception as e:
            print(f'  FAIL {fname}: {e}')
    print(f'Kodak: {len(downloaded)}/24 images')
    return sorted(downloaded)


def download_bsd500(dest='datasets/bsd500'):
    """Download BSD500 test images (200 images)."""
    import requests, tarfile
    os.makedirs(dest, exist_ok=True)
    existing = sorted([
        os.path.join(dest, f) for f in os.listdir(dest)
        if f.endswith('.jpg') or f.endswith('.png')
    ])
    if len(existing) >= 100:
        print(f'BSD500: {len(existing)} images already present')
        return existing

    url = 'https://www2.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/BSR/BSR_bsds500.tgz'
    print('Downloading BSD500 archive (~70MB)...')
    try:
        r = requests.get(url, timeout=180, stream=True)
        if r.status_code == 200:
            buf = io.BytesIO(r.content)
            with tarfile.open(fileobj=buf, mode='r:gz') as tar:
                # Extract test + train + val images
                imgs = [m for m in tar.getmembers()
                        if '/images/' in m.name and
                        (m.name.endswith('.jpg') or m.name.endswith('.png'))]
                for m in imgs:
                    fname = os.path.basename(m.name)
                    fpath = os.path.join(dest, fname)
                    f = tar.extractfile(m)
                    if f:
                        with open(fpath, 'wb') as out:
                            out.write(f.read())
            result = sorted([
                os.path.join(dest, f) for f in os.listdir(dest)
                if f.endswith('.jpg') or f.endswith('.png')
            ])
            print(f'  BSD500: extracted {len(result)} images')
            return result
        else:
            print(f'  BSD500 download failed: HTTP {r.status_code}')
            return []
    except Exception as e:
        print(f'  BSD500 download error: {e}')
        return []


def download_div2k(dest='datasets/div2k', split='train'):
    """
    Download DIV2K training set (800 images, ~2K resolution).
    Standard dataset for super-resolution research.
    """
    import requests, zipfile
    os.makedirs(dest, exist_ok=True)
    existing = sorted([
        os.path.join(dest, f) for f in os.listdir(dest)
        if f.endswith('.png')
    ])
    if len(existing) >= 400:
        print(f'DIV2K: {len(existing)} images already present')
        return existing

    url = 'http://data.vision.ee.ethz.ch/cvl/DIV2K/DIV2K_train_HR.zip'
    print('Downloading DIV2K training set (~3.3GB — this takes a few minutes)...')
    try:
        r = requests.get(url, timeout=600, stream=True)
        if r.status_code == 200:
            zip_path = os.path.join(dest, '_div2k.zip')
            with open(zip_path, 'wb') as f:
                for chunk in r.iter_content(chunk_size=8192*16):
                    f.write(chunk)
            with zipfile.ZipFile(zip_path, 'r') as z:
                for member in z.namelist():
                    if member.endswith('.png'):
                        fname = os.path.basename(member)
                        if fname:
                            with z.open(member) as src, \
                                 open(os.path.join(dest, fname), 'wb') as dst:
                                dst.write(src.read())
            os.remove(zip_path)
            result = sorted([
                os.path.join(dest, f) for f in os.listdir(dest)
                if f.endswith('.png')
            ])
            print(f'  DIV2K: extracted {len(result)} images')
            return result
        else:
            print(f'  DIV2K download failed: HTTP {r.status_code}')
            return []
    except Exception as e:
        print(f'  DIV2K download error: {e}')
        return []


def download_datasets(data_dir='datasets', datasets=('kodak', 'bsd500', 'div2k')):
    """Download all requested datasets and return combined image paths."""
    all_paths = []
    if 'kodak' in datasets:
        all_paths += download_kodak(os.path.join(data_dir, 'kodak'))
    if 'bsd500' in datasets:
        all_paths += download_bsd500(os.path.join(data_dir, 'bsd500'))
    if 'div2k' in datasets:
        all_paths += download_div2k(os.path.join(data_dir, 'div2k'))
    print(f'\nTotal training images: {len(all_paths)}')
    return all_paths


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 3: Training Pair Generation
# ═══════════════════════════════════════════════════════════════════════════════

def generate_training_pair(image_path, time_budget=60):
    """
    Run fractal encode/decode on one image, return (decoded_Y, original_Y).
    Both are 2D uint8 arrays of the Y (luminance) channel.
    """
    try:
        img_raw = np.array(Image.open(image_path).convert('RGB'))

        # Skip very small images
        if img_raw.shape[0] < 64 or img_raw.shape[1] < 64:
            return None

        # Limit large images to keep training time reasonable
        max_dim = 768
        h, w = img_raw.shape[:2]
        if max(h, w) > max_dim:
            scale = max_dim / max(h, w)
            new_h, new_w = int(h * scale), int(w * scale)
            img_raw = np.array(Image.fromarray(img_raw).resize(
                (new_w, new_h), Image.LANCZOS))

        img, orig_H, orig_W = pad_to_block_multiple(img_raw)
        H_pad, W_pad = img.shape[:2]

        ycbcr = rgb_to_ycbcr(img)
        original_y = ycbcr[:orig_H, :orig_W, 0]

        cfg = analyse_image(ycbcr[:,:,0], time_budget)
        y_tf, _ = encode_channel_gpu(ycbcr[:,:,0], cfg)
        decoded_y = decode_fractal(y_tf, (H_pad, W_pad), N_ITERATIONS)
        decoded_y = decoded_y[:orig_H, :orig_W]

        return decoded_y, original_y

    except Exception as e:
        print(f'  ERROR on {os.path.basename(image_path)}: {e}')
        return None


def extract_patches(decoded_y, original_y, patch_size=64, stride=32):
    """Extract overlapping patches from a (decoded, original) Y channel pair."""
    H, W = decoded_y.shape
    patches_in, patches_out = [], []

    for y in range(0, H - patch_size + 1, stride):
        for x in range(0, W - patch_size + 1, stride):
            p_in  = decoded_y[y:y+patch_size, x:x+patch_size].astype(np.float32) / 255.0
            p_out = original_y[y:y+patch_size, x:x+patch_size].astype(np.float32) / 255.0
            patches_in.append(p_in)
            patches_out.append(p_out)

            # Data augmentation: horizontal flip
            patches_in.append(np.fliplr(p_in).copy())
            patches_out.append(np.fliplr(p_out).copy())

    return patches_in, patches_out


def generate_all_pairs(image_paths, output_dir='training_pairs',
                       patch_size=64, stride=32, max_images=None):
    """
    Generate training pairs from all images. Saves patches as .npz files.
    Returns paths to saved files.
    """
    os.makedirs(output_dir, exist_ok=True)

    if max_images:
        image_paths = image_paths[:max_images]

    all_inputs, all_targets = [], []
    n = len(image_paths)

    for i, path in enumerate(image_paths):
        print(f'[{i+1}/{n}] Processing {os.path.basename(path)}...')
        result = generate_training_pair(path)
        if result is None:
            continue

        decoded_y, original_y = result
        p_in, p_out = extract_patches(decoded_y, original_y, patch_size, stride)
        all_inputs.extend(p_in)
        all_targets.extend(p_out)
        print(f'  → {len(p_in)} patches (total: {len(all_inputs)})')

        # Save incrementally every 50 images
        if (i + 1) % 50 == 0 or (i + 1) == n:
            save_path = os.path.join(output_dir, f'pairs_batch_{i+1}.npz')
            np.savez_compressed(save_path,
                                inputs=np.array(all_inputs),
                                targets=np.array(all_targets))
            print(f'  Saved checkpoint: {save_path} ({len(all_inputs)} patches)')

    # Final save
    final_path = os.path.join(output_dir, 'all_pairs.npz')
    np.savez_compressed(final_path,
                        inputs=np.array(all_inputs),
                        targets=np.array(all_targets))
    print(f'\n=== Generated {len(all_inputs)} training patches ===')
    print(f'Saved to {final_path}')
    return final_path


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 4: CNN Model Architecture
# ═══════════════════════════════════════════════════════════════════════════════

class EdgeAwareResidualCNN(nn.Module):
    """
    Lightweight residual CNN for fractal post-decode enhancement.

    Learns to predict and add back the high-frequency content
    (edges, texture) destroyed by fractal's 2× downsampling lowpass filter.

    Architecture:
        4 convolutional layers with residual learning.
        Input:  (B, 1, H, W)  — fractal-decoded Y channel
        Output: (B, 1, H, W)  — enhanced Y channel

    Parameters: ~37K (runs in <5ms per image on T4)
    """
    def __init__(self, n_channels=64, n_layers=4):
        super().__init__()
        layers = []
        # First layer: 1 input channel (Y) → n_channels
        layers.append(nn.Conv2d(1, n_channels, 3, padding=1))
        layers.append(nn.ReLU(inplace=True))
        # Hidden layers
        for _ in range(n_layers - 2):
            layers.append(nn.Conv2d(n_channels, n_channels, 3, padding=1))
            layers.append(nn.ReLU(inplace=True))
        # Final layer: n_channels → 1 (residual prediction, no activation)
        layers.append(nn.Conv2d(n_channels, 1, 3, padding=1))

        self.net = nn.Sequential(*layers)

    def forward(self, x):
        # Residual learning: predict the correction, add to input
        return x + self.net(x)


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 5: Loss Functions
# ═══════════════════════════════════════════════════════════════════════════════

class SSIMLoss(nn.Module):
    """Differentiable SSIM loss (1 - SSIM) for single-channel images."""
    def __init__(self, window_size=11, sigma=1.5):
        super().__init__()
        self.window_size = window_size
        # Create Gaussian window
        coords = torch.arange(window_size, dtype=torch.float32) - window_size // 2
        g = torch.exp(-(coords ** 2) / (2 * sigma ** 2))
        g = g / g.sum()
        window = g.unsqueeze(1) @ g.unsqueeze(0)  # 2D Gaussian
        self.register_buffer('window', window.unsqueeze(0).unsqueeze(0))  # (1,1,H,W)

    def forward(self, pred, target):
        C1 = 0.01 ** 2
        C2 = 0.03 ** 2

        mu1 = torch.nn.functional.conv2d(pred, self.window, padding=self.window_size//2)
        mu2 = torch.nn.functional.conv2d(target, self.window, padding=self.window_size//2)

        mu1_sq  = mu1 ** 2
        mu2_sq  = mu2 ** 2
        mu1_mu2 = mu1 * mu2

        sigma1_sq = torch.nn.functional.conv2d(
            pred * pred, self.window, padding=self.window_size//2) - mu1_sq
        sigma2_sq = torch.nn.functional.conv2d(
            target * target, self.window, padding=self.window_size//2) - mu2_sq
        sigma12 = torch.nn.functional.conv2d(
            pred * target, self.window, padding=self.window_size//2) - mu1_mu2

        ssim = ((2 * mu1_mu2 + C1) * (2 * sigma12 + C2)) / \
               ((mu1_sq + mu2_sq + C1) * (sigma1_sq + sigma2_sq + C2))

        return 1.0 - ssim.mean()


class VGGPerceptualLoss(nn.Module):
    """
    Perceptual loss using VGG16 conv3_3 features.
    Captures texture and structural similarity beyond pixel-level MSE.
    """
    def __init__(self):
        super().__init__()
        from torchvision import models
        vgg = models.vgg16(weights=models.VGG16_Weights.DEFAULT)
        # Use features up to conv3_3 (layer index 16)
        self.features = nn.Sequential(*list(vgg.features[:16]))
        for p in self.features.parameters():
            p.requires_grad = False
        # VGG normalisation
        self.register_buffer('mean', torch.tensor([0.485, 0.456, 0.406]).view(1,3,1,1))
        self.register_buffer('std', torch.tensor([0.229, 0.224, 0.225]).view(1,3,1,1))

    def forward(self, pred, target):
        # Expand single-channel to 3-channel for VGG
        pred_3   = pred.expand(-1, 3, -1, -1)
        target_3 = target.expand(-1, 3, -1, -1)
        # Normalise to VGG input range
        pred_n   = (pred_3 - self.mean) / self.std
        target_n = (target_3 - self.mean) / self.std
        # Feature distance
        return torch.nn.functional.mse_loss(
            self.features(pred_n), self.features(target_n))


class CompositeLoss(nn.Module):
    """
    Combined loss: α·MSE + β·(1-SSIM) + γ·VGG_perceptual

    MSE drives PSNR directly.
    SSIM captures structural/edge quality.
    VGG perceptual captures texture quality.
    """
    def __init__(self, alpha=1.0, beta=0.1, gamma=0.01, device='cuda'):
        super().__init__()
        self.alpha = alpha
        self.beta  = beta
        self.gamma = gamma
        self.mse_loss  = nn.MSELoss()
        self.ssim_loss = SSIMLoss().to(device)
        self.vgg_loss  = VGGPerceptualLoss().to(device)

    def forward(self, pred, target):
        l_mse  = self.mse_loss(pred, target)
        l_ssim = self.ssim_loss(pred, target)
        l_vgg  = self.vgg_loss(pred, target)
        return self.alpha * l_mse + self.beta * l_ssim + self.gamma * l_vgg


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 6: PyTorch Dataset
# ═══════════════════════════════════════════════════════════════════════════════

class FractalPatchDataset(Dataset):
    """Dataset of (decoded_Y_patch, original_Y_patch) pairs."""

    def __init__(self, npz_path):
        data = np.load(npz_path)
        self.inputs  = data['inputs']   # (N, H, W) float32 in [0, 1]
        self.targets = data['targets']  # (N, H, W) float32 in [0, 1]
        print(f'Loaded {len(self.inputs)} patches from {npz_path}')

    def __len__(self):
        return len(self.inputs)

    def __getitem__(self, idx):
        x = torch.from_numpy(self.inputs[idx]).unsqueeze(0)   # (1, H, W)
        y = torch.from_numpy(self.targets[idx]).unsqueeze(0)  # (1, H, W)
        return x, y


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 7: Training Loop
# ═══════════════════════════════════════════════════════════════════════════════

def train_cnn(pairs_path, output_path='fractal_cnn_weights.pt',
              epochs=80, batch_size=32, lr=1e-3, val_split=0.1,
              device=None):
    """
    Train the EdgeAwareResidualCNN on fractal decode training pairs.

    Args:
        pairs_path:  Path to .npz file with 'inputs' and 'targets' arrays
        output_path: Where to save the trained weights
        epochs:      Number of training epochs
        batch_size:  Batch size for training
        lr:          Initial learning rate
        val_split:   Fraction of data used for validation
        device:      'cuda' or 'cpu' (auto-detected if None)
    """
    if device is None:
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print(f'Training on {device}')

    # Load dataset
    dataset = FractalPatchDataset(pairs_path)
    n_val   = int(len(dataset) * val_split)
    n_train = len(dataset) - n_val
    train_ds, val_ds = torch.utils.data.random_split(
        dataset, [n_train, n_val],
        generator=torch.Generator().manual_seed(42))

    train_loader = DataLoader(train_ds, batch_size=batch_size, shuffle=True,
                              num_workers=2, pin_memory=True)
    val_loader   = DataLoader(val_ds, batch_size=batch_size, shuffle=False,
                              num_workers=2, pin_memory=True)

    print(f'Train: {n_train} patches, Val: {n_val} patches')

    # Model
    model = EdgeAwareResidualCNN(n_channels=64, n_layers=4).to(device)
    n_params = sum(p.numel() for p in model.parameters())
    print(f'Model: {n_params:,} parameters ({n_params*4/1024:.1f} KB)')

    # Loss and optimizer
    criterion = CompositeLoss(alpha=1.0, beta=0.1, gamma=0.01, device=device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

    best_val_loss = float('inf')
    best_val_psnr = 0.0
    history = []

    for epoch in range(epochs):
        # ── Train ──────────────────────────────────────────────────────
        model.train()
        train_loss = 0.0
        for batch_x, batch_y in train_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            pred = model(batch_x)
            loss = criterion(pred, batch_y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            train_loss += loss.item() * batch_x.size(0)
        train_loss /= n_train

        # ── Validate ───────────────────────────────────────────────────
        model.eval()
        val_loss = 0.0
        val_mse  = 0.0
        with torch.no_grad():
            for batch_x, batch_y in val_loader:
                batch_x, batch_y = batch_x.to(device), batch_y.to(device)
                pred = model(batch_x)
                val_loss += criterion(pred, batch_y).item() * batch_x.size(0)
                val_mse  += torch.nn.functional.mse_loss(pred, batch_y).item() * batch_x.size(0)
        val_loss /= n_val
        val_mse  /= n_val
        val_psnr = 10 * math.log10(1.0 / val_mse) if val_mse > 0 else 100.0

        scheduler.step()

        history.append({
            'epoch': epoch + 1,
            'train_loss': round(train_loss, 6),
            'val_loss': round(val_loss, 6),
            'val_psnr': round(val_psnr, 2),
            'lr': optimizer.param_groups[0]['lr'],
        })

        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(f'  Epoch {epoch+1:3d}/{epochs}  '
                  f'train={train_loss:.6f}  val={val_loss:.6f}  '
                  f'PSNR={val_psnr:.2f} dB  lr={optimizer.param_groups[0]["lr"]:.1e}')

        # Save best model
        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_val_psnr = val_psnr
            torch.save(model.state_dict(), output_path)

    # Final report
    model_size = os.path.getsize(output_path) / 1024
    print(f'\n{"="*50}')
    print(f'  Training complete')
    print(f'  Best val PSNR: {best_val_psnr:.2f} dB')
    print(f'  Model saved:   {output_path} ({model_size:.1f} KB)')
    print(f'{"="*50}')

    # Save training history
    hist_path = output_path.replace('.pt', '_history.json')
    with open(hist_path, 'w') as f:
        json.dump(history, f, indent=2)
    print(f'  History:       {hist_path}')

    return model, history


# ═══════════════════════════════════════════════════════════════════════════════
# SECTION 8: CLI Entry Point
# ═══════════════════════════════════════════════════════════════════════════════

def main():
    parser = argparse.ArgumentParser(
        description='Train CNN post-decoder for fractal image compression')
    parser.add_argument('--phase', default='all',
                        choices=['download', 'generate', 'train', 'all'],
                        help='Which phase to run (default: all)')
    parser.add_argument('--datasets', default='kodak,bsd500,div2k',
                        help='Comma-separated datasets to use')
    parser.add_argument('--data-dir', default='datasets',
                        help='Directory for downloaded datasets')
    parser.add_argument('--pairs-dir', default='training_pairs',
                        help='Directory for generated training pairs')
    parser.add_argument('--output', default='fractal_cnn_weights.pt',
                        help='Output path for trained weights')
    parser.add_argument('--epochs', type=int, default=80,
                        help='Training epochs')
    parser.add_argument('--batch-size', type=int, default=32,
                        help='Batch size')
    parser.add_argument('--lr', type=float, default=1e-3,
                        help='Initial learning rate')
    parser.add_argument('--patch-size', type=int, default=64,
                        help='Training patch size')
    parser.add_argument('--stride', type=int, default=32,
                        help='Patch extraction stride')
    parser.add_argument('--max-images', type=int, default=None,
                        help='Limit number of training images (for testing)')
    parser.add_argument('--device', default=None,
                        help='Device (cuda/cpu, auto-detected if not set)')

    args = parser.parse_args()
    datasets = [d.strip() for d in args.datasets.split(',')]

    print('=' * 60)
    print('  Fractal CNN Post-Decoder Training')
    print('=' * 60)
    print(f'  Datasets:   {datasets}')
    print(f'  Epochs:     {args.epochs}')
    print(f'  Patch size: {args.patch_size}')
    print(f'  Output:     {args.output}')
    print()

    pairs_path = os.path.join(args.pairs_dir, 'all_pairs.npz')

    if args.phase in ('download', 'all'):
        print('\n── Phase 1: Download Datasets ──')
        image_paths = download_datasets(args.data_dir, datasets)

    if args.phase in ('generate', 'all'):
        print('\n── Phase 2: Generate Training Pairs ──')
        # If we didn't just download, find existing images
        if args.phase == 'generate':
            image_paths = []
            for ds in datasets:
                ds_dir = os.path.join(args.data_dir, ds)
                if os.path.isdir(ds_dir):
                    image_paths += sorted([
                        os.path.join(ds_dir, f) for f in os.listdir(ds_dir)
                        if f.endswith(('.png', '.jpg', '.jpeg'))
                    ])
            print(f'Found {len(image_paths)} images')

        pairs_path = generate_all_pairs(
            image_paths, args.pairs_dir,
            args.patch_size, args.stride, args.max_images)

    if args.phase in ('train', 'all'):
        print('\n── Phase 3: Train CNN ──')
        if not os.path.exists(pairs_path):
            print(f'ERROR: Training pairs not found at {pairs_path}')
            print('Run with --phase generate first.')
            sys.exit(1)
        train_cnn(pairs_path, args.output, args.epochs,
                  args.batch_size, args.lr, device=args.device)


if __name__ == '__main__':
    main()
